/*
    TO BUILD AN END POINT I NEED NODEJS EXPRESS ESLINT AIRBNB AND MOCHA
    AFTER BUILDING THIS END POINT I WILL USE TRAVIC CI AND COVERALL

    STEP ONE: INSTALL EXPRESS, ESLINT AIRBNB AND MOCHA
    STEP TWO: WRITE TESTS FOR SIGN UP END POINT USING MOCHA
    SUBSTEP TWO ONE: TEST READING THE REQUEST SO THAT THE GOT REQUEST IS IN A CORRECT FORMAT
    SUBSTEP TWO TWO: TEST POSTING USER SO THAT A USER IS POSTED SUCCESSFULLY
    STEP THREE: BUILD A SIGN UP END POINT
    SUBSTEP THREE ONE: SIGNED UP MEMBERS OBJECT
    SUBSTEP THREE TWO: READ A SIGNING UP REQUEST
    SUBSTEP THREE THREE: CHECK POSSIBILITY
    SUBSTEP THREE FOUR: POST A SIGN UP MEMBER AND RESPOND POSSITIVELY IF NECESSARY
    SUBSTEP THREE FIVE: RESPOND NEGATIVELY IF NECESSARY

    ALL OF STAGE TWO MUST BE WRITTEN IN ESLINT AND AIRBNB
*/